# Project information
site_name: Cryptonite Wiki
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Basics: basics.md
  - Reversing: reverse.md
  - Pwning: pwn.md
  - Forensics: forensics.md
  - Steganography: steg.md
  - Cryptogrphy: crypto.md
  - Web: web.md
  - Research: research.md

site_author: Daksh Dadhania
site_description: >-
  Wiki site for cryptonite

# Repository
repo_name: Cryptonite-MIT
repo_url: https://github.com/Cryptonite-MIT

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary:  teal
      accent: lime    
  logo:   https://cryptonitemit.com/img/favicon.jpg
  extra:
    homepage: https://cryptonitemit.com/
  favicon: https://cryptonitemit.com/img/favicon.jpg
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Cryptonite-MIT
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/Cryptonite-MIT"  target="_blank" rel="noopener">Cryptonite MIT</a>